### ISSUE TITLE
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version

### ISSUE THREAD

**Issue by Baresound** [Gaunah/DegiroTransactionConverter#2]
Hey, thank you so much for your script. It saves my so much time and effort. I'm really thankful for it 🙏🏻

The log says: "/Degiro-to-Tradervue/DegiroToTradervue.py:54: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead."

Will you update the frame.append method when it will be removed from pandas in a future version so that the code will continue to work? 

Thanks for all you do, greatly appreciate it!

**Comment by Gaunah** [comment]
Hello,
Glad the script is helping you.
I haven't used it myself in a long time, so thanks for the heads up.
I will try to find time to fix it this weekend.

**Comment by Baresound** [comment]
You are a legend, thank you so much! Your script works just perfectly and in combination with an API key super fast as well.
Thanks for making my life easier with this tool 🍻
